### ISSUE TITLE
关于attention_mask的问题

### ISSUE THREAD

**Issue by grider-withourai** [jiamingkong/slam_asr_pytorch#1]
作者您好，我正在尝试用llama3和whisper v3复现SLAM-ASR的文章，有幸看到你的代码，通读过后发现有一点不是很理解，在[这个地方](https://github.com/jiamingkong/slam_asr_pytorch/blob/6f703447999a49ad0b4fa4f2f999c836fa1c6655/modeling/speech_encoder.py#L87)进行了一次attension_mask的计算，但是这个应该是对应音频进来时候的顺序，然而之后进行llm预测的时候应该是用的映射后的embedding。我看之后直接把这个mask和其他mask cat上了，这个mask跟映射后的音频embedding应该对应不上吧。请问这个地方是有什么含义吗？请麻烦指点一下，如果我的理解出错还麻烦指出，谢谢！

**Comment by jiamingkong** [comment]
您好，这里面的操作主要是为了让模型可以batch forward和backward。在一个batch里面因为音频长短和对应的transcription不同，所以组装的X，Y长短也会有不同。组装asr任务的时候，为了可以成批地使用hubert来编码音频，我们采用了您所提到的设计，具体来说，这个实现在我的理解里面应该是正确的。我们以`batch_size = 2`为例说明一下：

假设音频1 hubert编码后输出25帧，downsize之后是5帧。音频2 hubert编码后输出35帧，downsize之后是7帧。如果我们batch forward 两个音频到hubert里面，hubert应该输出的还是35帧 (`[2, 35, 384]`) ，只不过音频1的最后10帧没有意义，hubert也会对应地给出mask (`[2, 35]`的mask，第二行全1，第二行前25为1，后面为0)。这个mask会被您提到的地方计算成downsize之后的frame，新的表征downsize过后，是`[2, 7, llama_dim]`，新的mask则是`[2,7]`，第二行全1，第一行前5为1，后面为0。

这时候我们到了llama里面，llama 对应的batch输入都是等长的，因为我们贴进去的prompt前后都是一样的。假设在输入侧，我们在前面贴了3个token，后面贴了10个token，对应的prompt所在位置的mask都会是1；在答案侧（transcription），音频1有3个词，音频2有4个词，则这个batch输入的尺寸就会变成：`[2, 3 + 7 + 10 + 4, llama_dim]`，其中7取音频最长，4取transcription最长。对应的mask则是`[2, 24]`,其中第二行全1，第一行中间有两个0，最后结尾有一个0，分别对应音频缺的地方，和transcription缺的地方。

position embedding在llama的计算里面是通过mask的cumsum() 来计算的，所以缺少的地方恰好不会有positional id的变化。这样做，我们就可以比较轻松地实现batch forward了。
